application: message-graphs
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /assets
  static_dir: static
- url: /.*
  script: messages.app

libraries:
- name: jinja2
  version: latest

builtins:
- deferred: on
